services:
  - type: web
    name: wedding-platform
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: wedding-db
          property: connectionString

databases:
  - name: wedding-db
    databaseName: wedding_platform
    user: wedding_user
    plan: free